export const UserTypes = {
   USER_LOGIN_START: 'USER_LOGIN_START',
   USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
   USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
   USER_REGISTER_START: 'USER_REGISTER_START',
   USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
   USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
   USER_TOKEN_CHECK_SUCCESS: 'USER_TOKEN_CHECK_SUCCESS',
   USER_RESET_FORM: 'USER_RESET_FORM',
   USER_LOGOUT: 'USER_LOGOUT',
};

export const PostTypes = {
   TOGGLE_POST_MODAL: 'TOGGLE_POST_MODAL',
   CREATE_NEW_POST_SUCCESS: 'CREATE_NEW_POST_SUCCESS',
   CREATE_NEW_POST_FAILURE: 'CREATE_NEW_POST_FAILURE',
   GET_ALL_POSTS_SUCCESS: 'GET_ALL_POSTS_SUCCESS',
   GET_ALL_POSTS_FAILURE: 'GET_ALL_POSTS_FAILURE',
   GET_USER_POSTS_SUCCESS: 'GET_USER_POSTS_SUCCESS',
   GET_USER_POSTS_FAILURE: 'GET_USER_POSTS_FAILURE',
};
